production:
  storage: s3
  s3_credentials: "config/s3.yml"
  path: ":class/:attachment/:id_partition/:style.:extension"
  url: ":class/:attachment/:id_partition/:style.:extension"
  bucket: holidays-rafael-staging




#    :path => "images/:uuid_partition/:uuid/:style.:extension",
#    :storage => :s3,
#    :url => ':s3_authenticated_url', # generates an expiring url
#    :s3_credentials => File.join(Rails.root, 'config', 's3.yml'),
#    :s3_permissions => 'private',
#    :s3_protocol => 'https'





#    :storage => :s3,
#    :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
#    :path => ":attachment/:id/:style.:extension",
#    :url => ":attachment/:id/:style.:extension",    
#    :bucket => 'holidays-rafael-staging'